//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        [DisplayName("Team")]
        public string Name { get; set; }
        [DisplayName("GP")]
        public Nullable<int> Games { get; set; }
        [DisplayName("W")]
        public Nullable<int> Wins { get; set; }
        [DisplayName("L")]
        public Nullable<int> Losses { get; set; }
        [DisplayName("OT")]
        public Nullable<int> OvertimeLosses { get; set; }
        [DisplayName("PTS")]
        public Nullable<int> Points { get; set; }
        public int DivisionID { get; set; }
        public string Logo { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
