//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Division
    {
        public Division()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int DivisionID { get; set; }
        [DisplayName("Division")]
        public string Name { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
    }
}
